version: "3.7"

networks:
  that-chat-network:

services:
  java:
    image: uahuynhh/that-chat:prod
    env_file:
      - .env
    networks:
      that-chat-network:
        aliases:
          - "api"
  mongodb:
    image: 'mongo:6-jammy'
    environment:
      - 'MONGO_INITDB_DATABASE=chatbot'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    networks:
      that-chat-network:
        aliases:
          - "mongo"